language: node_js
node_js:
  - "0.10"
before_script:
  - cr ./scripts  --format json --maxcyc 5 --logicalor --silent
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
